services:
  sonar-labs:
    build:
      dockerfile: Dockerfile.prod
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      SONAR_PROFILES: openai
      PGPT_MODE: openai
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s   
